Update README.md
Docker images will need to be built beforehand.
Otherwise:

     $ docker run -e REDSHIFT_CONNECTION_STRING="user= password= host= port=5439 dbname=" -p 5000:5000 everythingme/redshift-console
     Unable to find image 'everythingme/redshift-console:latest' locally
     Pulling repository docker.io/everythingme/redshift-console
     Error: image everythingme/redshift-console:latest not found